package store

import (
	"context"
	"testing"
	"time"

	"github.com/tomlawesome/birdcage/internal/agentkind"
	"github.com/tomlawesome/birdcage/internal/db"
)

// openPeriod inserts an open span and returns nothing: the id is
// generated by the engine, and every assertion below reads spans back
// through ListStatePeriods rather than by id.
func openPeriod(t *testing.T, database *db.DB, canaryID, state string, startedAt time.Time) {
	t.Helper()
	if err := OpenStatePeriod(context.Background(), database, StatePeriod{
		CanaryID: canaryID, State: state, StartedAt: startedAt,
	}); err != nil {
		t.Fatalf("OpenStatePeriod(%s, %s): %v", canaryID, state, err)
	}
}

func openPeriodIDs(t *testing.T, database *db.DB) []StatePeriod {
	t.Helper()
	periods, err := OpenStatePeriods(context.Background(), database)
	if err != nil {
		t.Fatalf("OpenStatePeriods: %v", err)
	}
	return periods
}

// TestStatePeriodLifecycle walks one span through the three writes the
// recorder ever makes: open, close, reopen.
func TestStatePeriodLifecycle(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		start := mustParse(t, "2026-01-01T00:00:00Z")
		openPeriod(t, database, "canary-1", string(StateThrottled), start)

		open := openPeriodIDs(t, database)
		if len(open) != 1 {
			t.Fatalf("OpenStatePeriods returned %d spans, want 1: %+v", len(open), open)
		}
		if open[0].FlapCount != 1 {
			t.Errorf("FlapCount = %d on a fresh span, want 1", open[0].FlapCount)
		}

		endedAt := start.Add(time.Hour)
		if err := CloseStatePeriod(ctx, database, open[0].ID, endedAt, EndReasonCleared); err != nil {
			t.Fatalf("CloseStatePeriod: %v", err)
		}
		if got := openPeriodIDs(t, database); len(got) != 0 {
			t.Fatalf("OpenStatePeriods after close returned %d spans, want 0: %+v", len(got), got)
		}

		// Closing again must not move an end time already written.
		if err := CloseStatePeriod(ctx, database, open[0].ID, endedAt.Add(time.Hour), EndReasonUnobserved); err != nil {
			t.Fatalf("CloseStatePeriod (second): %v", err)
		}
		periods, err := ListStatePeriods(ctx, database, start.Add(-time.Hour), endedAt.Add(2*time.Hour), "")
		if err != nil {
			t.Fatalf("ListStatePeriods: %v", err)
		}
		if len(periods) != 1 {
			t.Fatalf("ListStatePeriods returned %d spans, want 1: %+v", len(periods), periods)
		}
		if periods[0].EndedAt == nil || !periods[0].EndedAt.Equal(endedAt) {
			t.Errorf("EndedAt = %v, want the first close at %v", periods[0].EndedAt, endedAt)
		}
		if periods[0].EndReason == nil || *periods[0].EndReason != EndReasonCleared {
			t.Errorf("EndReason = %v, want %q", periods[0].EndReason, EndReasonCleared)
		}

		if err := ReopenStatePeriod(ctx, database, open[0].ID); err != nil {
			t.Fatalf("ReopenStatePeriod: %v", err)
		}
		reopened := openPeriodIDs(t, database)
		if len(reopened) != 1 {
			t.Fatalf("OpenStatePeriods after reopen returned %d spans, want 1: %+v", len(reopened), reopened)
		}
		if reopened[0].FlapCount != 2 {
			t.Errorf("FlapCount after reopen = %d, want 2", reopened[0].FlapCount)
		}
		if !reopened[0].StartedAt.Equal(start) {
			t.Errorf("StartedAt after reopen = %v, want the original %v", reopened[0].StartedAt, start)
		}
	})
}

// TestCloseStatePeriodRejectsUnknownReason keeps end_reason a closed set
// in Go (migration 0010's comment), since no CHECK constraint enforces it.
func TestCloseStatePeriodRejectsUnknownReason(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		start := mustParse(t, "2026-01-01T00:00:00Z")
		openPeriod(t, database, "canary-1", string(StateThrottled), start)
		open := openPeriodIDs(t, database)
		err := CloseStatePeriod(context.Background(), database, open[0].ID, start.Add(time.Minute), "resolved")
		if err == nil {
			t.Fatal(`CloseStatePeriod(reason "resolved") = nil, want an error`)
		}
	})
}

// TestLatestClosedStatePeriodPicksTheLatest proves the "most recent
// closed span" lookup compares instants, not text: the later end time is
// written with a trimmed fractional second (no fraction at all), which a
// lexicographic comparison sorts BEFORE the earlier ".5" one.
func TestLatestClosedStatePeriodPicksTheLatest(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		start := mustParse(t, "2026-01-01T00:00:00Z")
		earlier := mustParse(t, "2026-01-01T00:10:00.5Z")
		later := mustParse(t, "2026-01-01T00:11:00Z")

		openPeriod(t, database, "canary-1", string(StateThrottled), start)
		first := openPeriodIDs(t, database)[0]
		if err := CloseStatePeriod(ctx, database, first.ID, earlier, EndReasonCleared); err != nil {
			t.Fatalf("CloseStatePeriod: %v", err)
		}
		openPeriod(t, database, "canary-1", string(StateThrottled), start.Add(10*time.Minute))
		second := openPeriodIDs(t, database)[0]
		if err := CloseStatePeriod(ctx, database, second.ID, later, EndReasonCleared); err != nil {
			t.Fatalf("CloseStatePeriod: %v", err)
		}

		got, err := LatestClosedStatePeriod(ctx, database, database.Engine, "canary-1", string(StateThrottled), start)
		if err != nil {
			t.Fatalf("LatestClosedStatePeriod: %v", err)
		}
		if got == nil {
			t.Fatal("LatestClosedStatePeriod = nil, want the later span")
		}
		if !got.EndedAt.Equal(later) {
			t.Errorf("LatestClosedStatePeriod ended at %v, want %v", got.EndedAt, later)
		}

		// notBefore excludes everything that closed earlier.
		got, err = LatestClosedStatePeriod(ctx, database, database.Engine, "canary-1", string(StateThrottled), later.Add(time.Second))
		if err != nil {
			t.Fatalf("LatestClosedStatePeriod (later cutoff): %v", err)
		}
		if got != nil {
			t.Errorf("LatestClosedStatePeriod past every end time = %+v, want nil", got)
		}
	})
}

// TestListStatePeriodsWindowAndOrder covers the overlap rule (a span that
// started before the window, one still open, one wholly outside) and the
// canary-name-then-start-time ordering the dashboard relies on.
func TestListStatePeriodsWindowAndOrder(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		enrolledAt := mustParse(t, "2026-01-01T00:00:00Z")
		for id, name := range map[string]string{"canary-b": "beta", "canary-a": "zulu"} {
			if err := InsertCanary(ctx, database, Canary{
				ID: id, Name: name, Lane: "lan", Kind: agentkind.Honeypot, HeartbeatIntervalS: 60, EnrolledAt: enrolledAt,
			}); err != nil {
				t.Fatalf("InsertCanary(%s): %v", id, err)
			}
		}

		since := mustParse(t, "2026-01-02T00:00:00Z")
		until := mustParse(t, "2026-01-03T00:00:00Z")

		// Wholly before the window: excluded.
		openPeriod(t, database, "canary-a", string(StateSilent), enrolledAt)
		stale := openPeriodIDs(t, database)[0]
		if err := CloseStatePeriod(ctx, database, stale.ID, enrolledAt.Add(time.Hour), EndReasonCleared); err != nil {
			t.Fatalf("CloseStatePeriod: %v", err)
		}
		// Started before the window, still open: included.
		openPeriod(t, database, "canary-a", string(StateThrottled), enrolledAt)
		// Inside the window: included.
		openPeriod(t, database, "canary-b", string(StateThrottled), since.Add(time.Hour))

		periods, err := ListStatePeriods(ctx, database, since, until, "")
		if err != nil {
			t.Fatalf("ListStatePeriods: %v", err)
		}
		if len(periods) != 2 {
			t.Fatalf("ListStatePeriods returned %d spans, want 2: %+v", len(periods), periods)
		}
		// "beta" (canary-b) sorts before "zulu" (canary-a) by name, not
		// by id -- which is what makes this assertion worth making.
		if periods[0].CanaryName != "beta" || periods[1].CanaryName != "zulu" {
			t.Errorf("order = %q, %q; want beta, zulu", periods[0].CanaryName, periods[1].CanaryName)
		}
		if periods[0].EndedAt != nil || periods[1].EndedAt != nil {
			t.Errorf("EndedAt = %v, %v; want both still open", periods[0].EndedAt, periods[1].EndedAt)
		}

		filtered, err := ListStatePeriods(ctx, database, since, until, "canary-b")
		if err != nil {
			t.Fatalf("ListStatePeriods(canary-b): %v", err)
		}
		if len(filtered) != 1 || filtered[0].CanaryID != "canary-b" {
			t.Errorf("ListStatePeriods(canary-b) = %+v, want only canary-b's span", filtered)
		}
	})
}

// TestSummarizeStatePeriodsClipsToWindow is the clipping rule: a span
// that started before the window counts only from its start, an open one
// only to its end, and a span clipped at both ends is still one span.
func TestSummarizeStatePeriodsClipsToWindow(t *testing.T) {
	since := mustParse(t, "2026-01-02T00:00:00Z")
	until := mustParse(t, "2026-01-03T00:00:00Z")
	endedInside := since.Add(2 * time.Hour)

	periods := []StatePeriod{
		// Straddles the whole window: 24h, not the days it really ran.
		{CanaryID: "c1", CanaryName: "one", State: string(StateSilent), StartedAt: since.Add(-48 * time.Hour)},
		// Starts before, ends inside: 2h.
		{CanaryID: "c1", CanaryName: "one", State: string(StateThrottled), StartedAt: since.Add(-time.Hour), EndedAt: &endedInside},
		// Wholly inside: 30m.
		{CanaryID: "c1", CanaryName: "one", State: string(StateThrottled), StartedAt: since.Add(3 * time.Hour), EndedAt: ptrTime(since.Add(3*time.Hour + 30*time.Minute))},
	}

	summary := SummarizeStatePeriods(periods, since, until)
	if len(summary) != 2 {
		t.Fatalf("summary has %d rows, want 2: %+v", len(summary), summary)
	}
	// Worst state first: silent outranks throttled (healthStateRank).
	if summary[0].State != string(StateSilent) || summary[1].State != string(StateThrottled) {
		t.Fatalf("summary order = %q, %q; want silent, throttled", summary[0].State, summary[1].State)
	}
	if summary[0].TotalS != 24*3600 || summary[0].LongestS != 24*3600 || summary[0].Count != 1 {
		t.Errorf("silent summary = %+v, want count 1 and 24h clipped to the window", summary[0])
	}
	if summary[1].Count != 2 {
		t.Errorf("throttled count = %d, want 2", summary[1].Count)
	}
	if summary[1].TotalS != 2*3600+1800 {
		t.Errorf("throttled total_s = %d, want %d", summary[1].TotalS, 2*3600+1800)
	}
	if summary[1].LongestS != 2*3600 {
		t.Errorf("throttled longest_s = %d, want %d", summary[1].LongestS, 2*3600)
	}
}

func ptrTime(t time.Time) *time.Time { return &t }

// TestApplyHealthStateActiveStates is issue #56's reason for touching
// health.go at all: the whole set of active states, worst first, with
// Status still naming only the head of it.
func TestApplyHealthStateActiveStates(t *testing.T) {
	now := mustParse(t, "2026-01-01T00:00:00Z")
	throttledSince := now.Add(-time.Minute)
	conflictSince := now.Add(-time.Hour)

	c := Canary{Status: string(StateSilent)}
	applyHealthState(&c, true, &throttledSince, false, false, 0, &conflictSince, now)

	want := []string{
		string(StateTokenConflict),
		string(StateSilent),
		string(StateNotDelivering),
		string(StateThrottled),
	}
	if len(c.ActiveStates) != len(want) {
		t.Fatalf("ActiveStates = %v, want %v", c.ActiveStates, want)
	}
	for i, state := range want {
		if c.ActiveStates[i] != state {
			t.Fatalf("ActiveStates = %v, want %v (worst first)", c.ActiveStates, want)
		}
	}
	if c.Status != string(StateTokenConflict) {
		t.Errorf("Status = %q, want %q -- the head of ActiveStates", c.Status, StateTokenConflict)
	}

	// Nothing active: "ok", and an empty set rather than a set holding
	// "ok" (which is the absence of a state, not one of them).
	healthy := Canary{Status: "ok"}
	applyHealthState(&healthy, false, nil, false, false, 0, nil, now)
	if healthy.Status != string(StateOK) || len(healthy.ActiveStates) != 0 {
		t.Errorf("healthy canary = status %q, states %v; want ok and no states", healthy.Status, healthy.ActiveStates)
	}
}
