package store

import (
	"context"
	"testing"
	"time"

	"github.com/tomlawesome/birdcage/internal/db"
)

// mailAt enqueues one message and returns nothing: ids are generated by
// the engine, and every assertion below reads rows back through
// LatestMail, DueMail or GetMailStatus rather than by id.
func mailAt(t *testing.T, database *db.DB, canaryID string, at time.Time) {
	t.Helper()
	id := canaryID
	var canary *string
	if canaryID != "" {
		canary = &id
	}
	if err := EnqueueMail(context.Background(), database, MailMessage{
		Kind:          string(MailKindTokenConflict),
		CanaryID:      canary,
		Subject:       "birdcage: a canary presented a revoked credential",
		Body:          "body for " + canaryID,
		CreatedAt:     at,
		NextAttemptAt: at,
	}); err != nil {
		t.Fatalf("EnqueueMail(%s, %s): %v", canaryID, at, err)
	}
}

func TestEnqueueMailRejectsBadInput(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		at := mustParse(t, "2026-09-17T09:00:00Z")
		base := MailMessage{
			Kind: string(MailKindTokenConflict), Subject: "s", Body: "b", CreatedAt: at, NextAttemptAt: at,
		}

		bad := base
		bad.Kind = "not_a_kind"
		if err := EnqueueMail(ctx, database, bad); err == nil {
			t.Error("EnqueueMail accepted an unknown kind")
		}

		bad = base
		bad.CreatedAt = time.Time{}
		if err := EnqueueMail(ctx, database, bad); err == nil {
			t.Error("EnqueueMail accepted a zero CreatedAt")
		}

		bad = base
		bad.Body = ""
		if err := EnqueueMail(ctx, database, bad); err == nil {
			t.Error("EnqueueMail accepted an empty body")
		}
	})
}

// A zero NextAttemptAt means "as soon as the next tick runs", which is
// what every caller wants and is defaulted rather than rejected.
func TestEnqueueMailDefaultsNextAttemptToCreatedAt(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		at := mustParse(t, "2026-09-17T09:00:00Z")
		if err := EnqueueMail(ctx, database, MailMessage{
			Kind: string(MailKindTokenConflict), Subject: "s", Body: "b", CreatedAt: at,
		}); err != nil {
			t.Fatalf("EnqueueMail: %v", err)
		}
		m, err := LatestMail(ctx, database, MailKindTokenConflict, "")
		if err != nil {
			t.Fatalf("LatestMail: %v", err)
		}
		if !m.NextAttemptAt.Equal(at) {
			t.Errorf("NextAttemptAt = %s, want %s", m.NextAttemptAt, at)
		}
		if m.Attempts != 0 || m.SentAt != nil || m.LastError != nil || m.SuppressedCount != 0 {
			t.Errorf("a fresh row is not fresh: %+v", m)
		}
	})
}

// DueMail is the sender's whole input: unsent, and due. The boundary is
// inclusive -- a message due exactly now is due.
func TestDueMailSelectsUnsentAndDue(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		now := mustParse(t, "2026-09-17T09:00:00Z")

		mailAt(t, database, "canary-a", now.Add(-2*time.Minute))
		mailAt(t, database, "canary-b", now.Add(-time.Minute))
		mailAt(t, database, "canary-c", now)
		mailAt(t, database, "canary-d", now.Add(time.Minute)) // not due yet

		due, err := DueMail(ctx, database, now)
		if err != nil {
			t.Fatalf("DueMail: %v", err)
		}
		if len(due) != 3 {
			t.Fatalf("DueMail returned %d messages, want 3: %+v", len(due), due)
		}
		// Oldest first, so a backlog drains in the order it was written.
		for i, want := range []string{"canary-a", "canary-b", "canary-c"} {
			if due[i].CanaryID == nil || *due[i].CanaryID != want {
				t.Errorf("due[%d] is %v, want %s", i, due[i].CanaryID, want)
			}
		}

		// Once sent, a message is never due again.
		if err := MarkMailSent(ctx, database, due[0].ID, now); err != nil {
			t.Fatalf("MarkMailSent: %v", err)
		}
		due, err = DueMail(ctx, database, now)
		if err != nil {
			t.Fatalf("DueMail after send: %v", err)
		}
		if len(due) != 2 {
			t.Errorf("DueMail after a send returned %d messages, want 2", len(due))
		}
	})
}

// A fractional second is where a text comparison would go wrong:
// RFC3339Nano trims trailing zeros, so "…:00Z" sorts after "…:00.5Z"
// lexicographically. Every comparison in this file is on parsed
// instants for exactly this reason.
func TestDueMailHandlesTrimmedFractionalSeconds(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		whole := mustParse(t, "2026-09-17T09:00:00Z")
		fractional := whole.Add(-500 * time.Millisecond)

		mailAt(t, database, "canary-fraction", fractional)
		mailAt(t, database, "canary-whole", whole)

		due, err := DueMail(ctx, database, whole)
		if err != nil {
			t.Fatalf("DueMail: %v", err)
		}
		if len(due) != 2 {
			t.Fatalf("DueMail returned %d messages, want both", len(due))
		}
		if due[0].CanaryID == nil || *due[0].CanaryID != "canary-fraction" {
			t.Errorf("the fractional-second message did not sort first: %+v", due)
		}
	})
}

func TestMarkMailSentIsIdempotent(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		now := mustParse(t, "2026-09-17T09:00:00Z")
		mailAt(t, database, "canary-a", now)

		m, err := LatestMail(ctx, database, MailKindTokenConflict, "canary-a")
		if err != nil {
			t.Fatalf("LatestMail: %v", err)
		}
		if err := MarkMailSent(ctx, database, m.ID, now); err != nil {
			t.Fatalf("MarkMailSent: %v", err)
		}
		// A second call must not move a send time already written.
		if err := MarkMailSent(ctx, database, m.ID, now.Add(time.Hour)); err != nil {
			t.Fatalf("MarkMailSent (second): %v", err)
		}
		again, err := LatestMail(ctx, database, MailKindTokenConflict, "canary-a")
		if err != nil {
			t.Fatalf("LatestMail: %v", err)
		}
		if again.SentAt == nil || !again.SentAt.Equal(now) {
			t.Errorf("SentAt = %v, want the first send time %s", again.SentAt, now)
		}
	})
}

// A send that eventually succeeds clears the error, so GET /api/mail
// stops reporting a row that is no longer failing.
func TestMarkMailSentClearsTheLastError(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		now := mustParse(t, "2026-09-17T09:00:00Z")
		mailAt(t, database, "canary-a", now)
		m, err := LatestMail(ctx, database, MailKindTokenConflict, "canary-a")
		if err != nil {
			t.Fatalf("LatestMail: %v", err)
		}
		if err := RecordMailFailure(ctx, database, m.ID, "could not send: server said no", now.Add(time.Minute)); err != nil {
			t.Fatalf("RecordMailFailure: %v", err)
		}
		if err := MarkMailSent(ctx, database, m.ID, now.Add(2*time.Minute)); err != nil {
			t.Fatalf("MarkMailSent: %v", err)
		}
		sent, err := LatestMail(ctx, database, MailKindTokenConflict, "canary-a")
		if err != nil {
			t.Fatalf("LatestMail: %v", err)
		}
		if sent.LastError != nil {
			t.Errorf("LastError = %q after a successful send, want nil", *sent.LastError)
		}
		if sent.Attempts != 1 {
			t.Errorf("Attempts = %d, want the failed attempt to be remembered", sent.Attempts)
		}
	})
}

func TestRecordMailFailureAccumulates(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		now := mustParse(t, "2026-09-17T09:00:00Z")
		mailAt(t, database, "canary-a", now)
		m, err := LatestMail(ctx, database, MailKindTokenConflict, "canary-a")
		if err != nil {
			t.Fatalf("LatestMail: %v", err)
		}

		for i := 1; i <= 3; i++ {
			next := now.Add(time.Duration(i) * time.Minute)
			if err := RecordMailFailure(ctx, database, m.ID, "attempt failed", next); err != nil {
				t.Fatalf("RecordMailFailure %d: %v", i, err)
			}
			got, err := LatestMail(ctx, database, MailKindTokenConflict, "canary-a")
			if err != nil {
				t.Fatalf("LatestMail: %v", err)
			}
			if got.Attempts != int64(i) {
				t.Errorf("Attempts = %d after %d failures", got.Attempts, i)
			}
			if !got.NextAttemptAt.Equal(next) {
				t.Errorf("NextAttemptAt = %s, want %s", got.NextAttemptAt, next)
			}
		}
	})
}

// LatestMail is the cooldown lookup: most recent for a canary and kind,
// sent or unsent alike.
func TestLatestMailIsTheMostRecent(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		now := mustParse(t, "2026-09-17T09:00:00Z")
		mailAt(t, database, "canary-a", now.Add(-2*time.Hour))
		mailAt(t, database, "canary-a", now.Add(-time.Hour))
		mailAt(t, database, "canary-b", now)

		m, err := LatestMail(ctx, database, MailKindTokenConflict, "canary-a")
		if err != nil {
			t.Fatalf("LatestMail: %v", err)
		}
		if !m.CreatedAt.Equal(now.Add(-time.Hour)) {
			t.Errorf("LatestMail(canary-a).CreatedAt = %s, want %s", m.CreatedAt, now.Add(-time.Hour))
		}

		// Unfiltered, it is the most recent of any canary.
		any, err := LatestMail(ctx, database, MailKindTokenConflict, "")
		if err != nil {
			t.Fatalf("LatestMail (any canary): %v", err)
		}
		if any.CanaryID == nil || *any.CanaryID != "canary-b" {
			t.Errorf("LatestMail (any canary) = %v, want canary-b", any.CanaryID)
		}

		none, err := LatestMail(ctx, database, MailKindTokenConflict, "canary-never")
		if err != nil {
			t.Fatalf("LatestMail (unknown canary): %v", err)
		}
		if none != nil {
			t.Errorf("LatestMail for a canary with no mail returned %+v, want nil", none)
		}
	})
}

// CountMailSince is the fleet cap's input. The boundary is inclusive: a
// message created exactly at `since` is inside the window.
func TestCountMailSinceBoundary(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		now := mustParse(t, "2026-09-17T09:00:00Z")
		since := now.Add(-time.Hour)

		mailAt(t, database, "canary-old", since.Add(-time.Second))
		mailAt(t, database, "canary-edge", since)
		mailAt(t, database, "canary-new", now)

		n, err := CountMailSince(ctx, database, database.Engine, since)
		if err != nil {
			t.Fatalf("CountMailSince: %v", err)
		}
		if n != 2 {
			t.Errorf("CountMailSince = %d, want 2 (the edge is inside the window)", n)
		}
	})
}

func TestBumpMailSuppressed(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		now := mustParse(t, "2026-09-17T09:00:00Z")
		mailAt(t, database, "canary-a", now)
		m, err := LatestMail(ctx, database, MailKindTokenConflict, "canary-a")
		if err != nil {
			t.Fatalf("LatestMail: %v", err)
		}
		for i := 0; i < 3; i++ {
			if err := BumpMailSuppressed(ctx, database, m.ID); err != nil {
				t.Fatalf("BumpMailSuppressed: %v", err)
			}
		}
		got, err := LatestMail(ctx, database, MailKindTokenConflict, "canary-a")
		if err != nil {
			t.Fatalf("LatestMail: %v", err)
		}
		if got.SuppressedCount != 3 {
			t.Errorf("SuppressedCount = %d, want 3", got.SuppressedCount)
		}
	})
}

// GetMailStatus is GET /api/mail's whole body. failing_since is the
// created_at of the oldest unsent row with a failed attempt behind it
// -- a row that is merely owed and has never been tried is not evidence
// that mail is broken.
func TestGetMailStatus(t *testing.T) {
	forEachEngine(t, func(t *testing.T, database *db.DB) {
		ctx := context.Background()
		now := mustParse(t, "2026-09-17T09:00:00Z")

		empty, err := GetMailStatus(ctx, database)
		if err != nil {
			t.Fatalf("GetMailStatus (empty): %v", err)
		}
		if empty.Pending != 0 || empty.LastSentAt != nil || empty.FailingSince != nil || empty.LastError != nil || empty.Suppressed != 0 {
			t.Errorf("an empty outbox reports %+v", empty)
		}

		// One sent, one failing (older), one failing (newer), one
		// merely owed.
		mailAt(t, database, "canary-sent", now.Add(-4*time.Hour))
		mailAt(t, database, "canary-old-fail", now.Add(-3*time.Hour))
		mailAt(t, database, "canary-new-fail", now.Add(-2*time.Hour))
		mailAt(t, database, "canary-untried", now.Add(-time.Hour))

		ids := map[string]int64{}
		for _, id := range []string{"canary-sent", "canary-old-fail", "canary-new-fail", "canary-untried"} {
			m, err := LatestMail(ctx, database, MailKindTokenConflict, id)
			if err != nil {
				t.Fatalf("LatestMail(%s): %v", id, err)
			}
			ids[id] = m.ID
		}

		if err := MarkMailSent(ctx, database, ids["canary-sent"], now.Add(-4*time.Hour)); err != nil {
			t.Fatalf("MarkMailSent: %v", err)
		}
		if err := RecordMailFailure(ctx, database, ids["canary-old-fail"], "could not send: the older failure", now.Add(time.Minute)); err != nil {
			t.Fatalf("RecordMailFailure: %v", err)
		}
		if err := RecordMailFailure(ctx, database, ids["canary-new-fail"], "could not send: the newer failure", now.Add(time.Minute)); err != nil {
			t.Fatalf("RecordMailFailure: %v", err)
		}
		if err := BumpMailSuppressed(ctx, database, ids["canary-untried"]); err != nil {
			t.Fatalf("BumpMailSuppressed: %v", err)
		}

		status, err := GetMailStatus(ctx, database)
		if err != nil {
			t.Fatalf("GetMailStatus: %v", err)
		}
		if status.Pending != 3 {
			t.Errorf("Pending = %d, want 3", status.Pending)
		}
		if status.LastSentAt == nil || !status.LastSentAt.Equal(now.Add(-4*time.Hour)) {
			t.Errorf("LastSentAt = %v, want %s", status.LastSentAt, now.Add(-4*time.Hour))
		}
		if status.FailingSince == nil || !status.FailingSince.Equal(now.Add(-3*time.Hour)) {
			t.Errorf("FailingSince = %v, want the oldest failing row's created_at %s", status.FailingSince, now.Add(-3*time.Hour))
		}
		if status.LastError == nil || *status.LastError != "could not send: the older failure" {
			t.Errorf("LastError = %v, want the same row FailingSince came from", status.LastError)
		}
		if status.Suppressed != 1 {
			t.Errorf("Suppressed = %d, want 1", status.Suppressed)
		}
	})
}
