package runcmd

import (
	"fmt"
	"io"
	"strings"

	"github.com/tomlawesome/birdcage/internal/agentkind"
	"github.com/tomlawesome/birdcage/internal/term"
)

// UpgradeInput is everything Upgrade needs to build one canary's
// upgrade command (issue #54): the copy-and-paste script `birdcage agent
// upgrade-command` prints when that canary's agent is running an older
// build than birdcage itself. A plain `docker restart` would keep the
// old image running, so this pulls every current image first, removes
// every container (dependants before the holder that owns their shared
// network namespace), presents the upgrade token, then re-runs each one
// in the same order enrolment printed them in -- never with a deploy
// token, see MockingbirdConfig.Token's own doc comment for why one is
// pointless here.
type UpgradeInput struct {
	Kind agentkind.Kind

	// UpgradeToken is the single-use token store.MintUpgradeToken
	// returned for this canary (ADR-0012's B4 amendment): 64 lowercase
	// hex characters, checked here, and printed unescaped like the CA
	// pin and the deploy token -- generated by birdcage, never supplied
	// by anyone. It reaches the new agent image on stdin only
	// (writeUpgradeTokenStep), never as an argument or an environment
	// variable.
	UpgradeToken string

	// AdvertiseHost, EnrolPort and Pin are birdcage's own current
	// runtime facts -- the same three values every current enrolment
	// uses, not something read back per canary.
	AdvertiseHost string
	EnrolPort     string
	Pin           string

	// AgentImage is Mockingbird's image reference for a honeypot,
	// Nightjar's for a scanner -- the caller resolves it from
	// agentkind.Lookup(Kind).Profile's own ImageEnv/DefaultImage, the
	// same resolution `birdcage agent enrol` already uses.
	AgentImage string

	// HolderImage, OpenCanaryImage and SMBLureImage are the caller's own
	// HolderImage()/OpenCanaryImage()/SMBLureImage() reads (below).
	// Honeypot only; a caller building a scanner's input may leave them
	// unset.
	HolderImage     string
	OpenCanaryImage string
	SMBLureImage    string

	// BaitNames and SegmentProfile are this canary's current
	// canary_settings values (store.ListCanarySettings) -- honeypot
	// only, empty when neither was ever set, matching
	// MockingbirdConfig's own fields.
	BaitNames      string
	SegmentProfile string

	// SMBLure, SMBWorkgroup and SMBShares are
	// store.CanaryUpgradeFacts' own fields. SMBLure nil means unknown --
	// this canary predates issue #54, which is the first thing that ever
	// recorded it -- and Upgrade must never guess which way (owner,
	// 2026-09-27: "treat lure as unknown ... never guess silently"): it
	// prints the lure's own commands commented, with a note to check
	// the host, rather than either running them or silently leaving
	// them out. SMBWorkgroup and SMBShares (exactly SMBShareCount
	// entries) are set only when SMBLure is non-nil and true.
	SMBLure      *bool
	SMBWorkgroup string
	SMBShares    []string
}

// Placeholders for a legacy canary's never-recorded SMB workgroup and
// share names -- SMBLure == nil means the operator's original
// --smb-workgroup/--smb-shares values (if any) were never stored at
// all (issue #54 is what started storing them), so there is nothing
// truer to print here than a marker the operator has to replace by
// hand after checking the host. Letters, digits and hyphens only,
// matching the character set parseSMBSettings itself accepts, even
// though nothing here validates them -- these never reach a live
// container uncommented.
const unknownSMBWorkgroupPlaceholder = "WORKGROUP-UNKNOWN-CHECK-HOST"

var unknownSMBSharePlaceholders = []string{
	"SHARE1-UNKNOWN-CHECK-HOST",
	"SHARE2-UNKNOWN-CHECK-HOST",
	"SHARE3-UNKNOWN-CHECK-HOST",
}

// Upgrade writes the full upgrade script for one canary. Returns an
// error naming the kind for anything Upgrade has no script for, the
// same "fail loudly, never invent" stance
// cmd/birdcage/canary.go's own runCanaryEnrol switch takes on an
// unregistered kind, and an error for a missing or malformed upgrade
// token.
//
// The whole script is one subshell group, `( set -e` on the first line
// and `)` on the last (owner, 2026-09-27: "it must be ONE copy, that
// runs completely from ONE paste into the host"). A shell reads the
// group to its closing parenthesis before running any of it, so a paste
// is never half-executed while the rest is still arriving; set -e stops
// it at the first failing step; and the EXIT trap names the step it
// stopped at, or says it finished. POSIX sh throughout -- no bash-only
// syntax -- so it runs the same pasted into bash, dash or busybox sh.
// The group must never be followed by `||` or `&&`: that would switch
// set -e off inside it.
func Upgrade(w io.Writer, in UpgradeInput) error {
	var body func(io.Writer, UpgradeInput) error
	switch in.Kind {
	case agentkind.Honeypot:
		body = upgradeHoneypot
	case agentkind.Scanner:
		body = upgradeScanner
	default:
		return fmt.Errorf("runcmd: Upgrade: no upgrade script registered for kind %q", in.Kind)
	}
	if !validUpgradeToken(in.UpgradeToken) {
		return fmt.Errorf("runcmd: Upgrade: upgrade token must be %d lowercase hex characters", upgradeTokenLen)
	}
	if err := writeLines(w, []string{
		"( set -e",
		`trap 'rc=$?; if [ "$rc" -eq 0 ]; then echo "birdcage upgrade: done"; else echo "birdcage upgrade stopped at: $step (nothing after it ran)" >&2; fi' EXIT`,
	}); err != nil {
		return err
	}
	if err := body(w, in); err != nil {
		return err
	}
	return writeLines(w, []string{")"})
}

// upgradeTokenLen is a minted upgrade token's length: 32 random bytes,
// hex-encoded (internal/store's upgradeTokenBytes).
const upgradeTokenLen = 64

func validUpgradeToken(t string) bool {
	if len(t) != upgradeTokenLen {
		return false
	}
	for i := 0; i < len(t); i++ {
		c := t[i]
		if (c < '0' || c > '9') && (c < 'a' || c > 'f') {
			return false
		}
	}
	return true
}

func blank(w io.Writer) error {
	_, err := fmt.Fprintln(w)
	return err
}

// step writes the line naming the step the lines after it belong to --
// what Upgrade's EXIT trap prints if one of them fails. name is always
// one of this file's own constant phrases, never a caller's value, so it
// is written unescaped inside single quotes.
func step(w io.Writer, name string) error {
	return writeLines(w, []string{fmt.Sprintf("step='%s'", name)})
}

// writeUpgradeTokenStep writes the step that hands the new agent image
// the upgrade token: a throwaway container of that image, run with the
// agent's state volume mounted read-only so it can present the token
// over the agent's own credential and cannot write anything, reading
// the token from stdin (`echo` is a shell builtin, so the token is in no
// process's arguments). It runs after the old agent is removed and
// before the new one starts, because B4 compares builds on the new
// agent's very first heartbeat and the window has to exist by then.
//
// `|| true`: a refused token is not a reason to leave the canary with no
// agent at all. The subcommand has already said why; the upgrade goes
// on, and the worst case is the credential_conflict this token exists
// to avoid.
func writeUpgradeTokenStep(w io.Writer, token, image, volumeFlag, networkLine string) error {
	lines := []string{fmt.Sprintf(`echo %s | docker run --rm -i \`, token)}
	if networkLine != "" {
		lines = append(lines, networkLine)
	}
	lines = append(lines,
		"  --read-only --cap-drop ALL --security-opt no-new-privileges \\",
		fmt.Sprintf("  %s \\", volumeFlag),
		fmt.Sprintf("  %s upgrade-token || true", term.Escape(image)),
	)
	if err := step(w, "present the upgrade token"); err != nil {
		return err
	}
	return writeLines(w, lines)
}

// upgradeScanner builds a scanner's upgrade script: Nightjar is a
// single standalone container (no shared network namespace, no
// dependants), so this is the simplest of the two -- pull, remove,
// present the token, re-run.
func upgradeScanner(w io.Writer, in UpgradeInput) error {
	if err := step(w, "pull the current image"); err != nil {
		return err
	}
	if err := writeLines(w, []string{fmt.Sprintf("docker pull %s", term.Escape(in.AgentImage))}); err != nil {
		return err
	}
	if err := blank(w); err != nil {
		return err
	}
	if err := step(w, "remove the old container"); err != nil {
		return err
	}
	if err := writeLines(w, []string{fmt.Sprintf("docker rm -f %s", NightjarContainerName)}); err != nil {
		return err
	}
	if err := blank(w); err != nil {
		return err
	}
	if err := writeUpgradeTokenStep(w, in.UpgradeToken, in.AgentImage, "-v nightjar-state:/var/lib/nightjar:ro", ""); err != nil {
		return err
	}
	if err := blank(w); err != nil {
		return err
	}
	if err := step(w, "start nightjar"); err != nil {
		return err
	}
	return WriteNightjarRun(w, NightjarConfig{
		AdvertiseHost: in.AdvertiseHost,
		EnrolPort:     in.EnrolPort,
		Pin:           in.Pin,
		Token:         "",
		Image:         in.AgentImage,
	})
}

// upgradeHoneypot builds a honeypot's upgrade script: up to four
// containers sharing the holder's network namespace, so every image is
// pulled before any container is removed, and every removal has to land
// before the holder's own -- a dependant removed after its own
// namespace is gone fails outright, which is why "dependants before
// holder" is not just tidiness.
func upgradeHoneypot(w io.Writer, in UpgradeInput) error {
	lureOn := in.SMBLure != nil && *in.SMBLure
	lureOff := in.SMBLure != nil && !*in.SMBLure

	pulls := []string{
		fmt.Sprintf("docker pull %s", term.Escape(in.AgentImage)),
		fmt.Sprintf("docker pull %s", term.Escape(in.HolderImage)),
		fmt.Sprintf("docker pull %s", term.Escape(in.OpenCanaryImage)),
	}
	if lureOn {
		pulls = append(pulls, fmt.Sprintf("docker pull %s", term.Escape(in.SMBLureImage)))
	}
	if err := step(w, "pull the current images"); err != nil {
		return err
	}
	if err := writeLines(w, pulls); err != nil {
		return err
	}
	if err := blank(w); err != nil {
		return err
	}

	// Dependants before the holder -- the reverse of the enrolment
	// order below, since each one joined the holder's namespace only
	// once the holder already existed.
	var rms []string
	if lureOn {
		rms = append(rms, fmt.Sprintf("docker rm -f %s", SMBLureContainerName))
	}
	rms = append(rms,
		fmt.Sprintf("docker rm -f %s", OpenCanaryContainerName),
		fmt.Sprintf("docker rm -f %s", MockingbirdContainerName),
		fmt.Sprintf("docker rm -f %s", HolderContainerName),
	)
	if err := step(w, "remove the old containers"); err != nil {
		return err
	}
	if err := writeLines(w, rms); err != nil {
		return err
	}
	if err := blank(w); err != nil {
		return err
	}

	// Re-run in enrolment order: holder, Mockingbird, OpenCanary, the
	// lure -- runCanaryEnrol's own comment on that order still applies
	// (Mockingbird's receiver must be listening before OpenCanary's
	// first webhook attempt, and the lure joins the holder only once it
	// exists). The upgrade token goes between the holder and Mockingbird:
	// it needs the holder's network namespace (so birdcage sees it from
	// the canary's own address) and must land before Mockingbird's first
	// heartbeat -- writeUpgradeTokenStep's own comment.
	if err := step(w, "start the address holder"); err != nil {
		return err
	}
	if err := WriteHolderRun(w, HolderConfig{Image: in.HolderImage, SMBLure: lureOn}); err != nil {
		return err
	}
	if err := blank(w); err != nil {
		return err
	}

	if err := writeUpgradeTokenStep(w, in.UpgradeToken, in.AgentImage,
		"-v mockingbird-state:/var/lib/mockingbird:ro",
		fmt.Sprintf("  --network container:%s \\", HolderContainerName)); err != nil {
		return err
	}
	if err := blank(w); err != nil {
		return err
	}

	if err := step(w, "start mockingbird"); err != nil {
		return err
	}
	if err := WriteMockingbirdRun(w, MockingbirdConfig{
		AdvertiseHost:  in.AdvertiseHost,
		EnrolPort:      in.EnrolPort,
		Pin:            in.Pin,
		Token:          "",
		Image:          in.AgentImage,
		SMBLure:        lureOn,
		BaitNames:      in.BaitNames,
		SegmentProfile: in.SegmentProfile,
	}); err != nil {
		return err
	}
	if err := blank(w); err != nil {
		return err
	}

	if err := step(w, "start opencanary"); err != nil {
		return err
	}
	if err := WriteOpenCanaryRun(w, OpenCanaryConfig{Image: in.OpenCanaryImage}); err != nil {
		return err
	}

	if err := blank(w); err != nil {
		return err
	}
	switch {
	case lureOn:
		if err := step(w, "start the smb lure"); err != nil {
			return err
		}
		return WriteSMBLureRun(w, SMBLureConfig{Image: in.SMBLureImage, Workgroup: in.SMBWorkgroup, Shares: in.SMBShares})
	case lureOff:
		// Matching cmd/birdcage/canary.go's own enrolment-time line for
		// the same decision ("smb lure off by request"): one line, no
		// commands, so there is nothing here for an operator to
		// mistakenly run.
		_, err := fmt.Fprintln(w, "# smb lure off for this canary: no smb-lure container to pull, remove or re-run")
		return err
	default:
		return writeUnknownSMBLureBlock(w, in)
	}
}

// writeUnknownSMBLureBlock is upgradeHoneypot's SMBLure == nil case: a
// canary enrolled before issue #54 ever recorded whether it had the SMB
// lure at all. Printing nothing would silently drop a lure that is
// still running; printing a live command would silently create one
// that never existed. Neither is a guess this function gets to make, so
// it prints the commands commented out, with a note to check the host
// first, and placeholders (unknownSMBWorkgroupPlaceholder/
// unknownSMBSharePlaceholders) standing in for a workgroup and share
// names that were never recorded either -- an operator who confirms the
// lure exists still has to fill those in by hand or read them off the
// running container.
func writeUnknownSMBLureBlock(w io.Writer, in UpgradeInput) error {
	note := []string{
		"# SMB lure: unknown for this canary -- it was enrolled before birdcage started",
		"# recording this (issue #54). Check the canary host for a running smb-lure",
		"# container (docker ps -a --filter name=smb-lure) before relying on anything",
		"# below. Its workgroup and share names were never recorded either, so the",
		"# commented command below uses placeholders -- replace them with what the",
		"# host is actually running, or leave the lure off if `docker ps -a` finds none.",
	}
	if err := writeLines(w, note); err != nil {
		return err
	}

	var body strings.Builder
	if err := WriteSMBLureRun(&body, SMBLureConfig{
		Image:     in.SMBLureImage,
		Workgroup: unknownSMBWorkgroupPlaceholder,
		Shares:    unknownSMBSharePlaceholders,
	}); err != nil {
		return err
	}

	commented := []string{
		"# " + fmt.Sprintf("docker pull %s", term.Escape(in.SMBLureImage)),
		"# " + fmt.Sprintf("docker rm -f %s", SMBLureContainerName),
	}
	for _, line := range strings.Split(strings.TrimRight(body.String(), "\n"), "\n") {
		commented = append(commented, "# "+line)
	}
	return writeLines(w, commented)
}
